//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Input_ActionSet_default p__default;
        
        private static SteamVR_Input_ActionSet_gemAbilities p_gemAbilities;
        
        private static SteamVR_Input_ActionSet_locomotion p_locomotion;
        
        public static SteamVR_Input_ActionSet_default _default
        {
            get
            {
                return SteamVR_Actions.p__default.GetCopy<SteamVR_Input_ActionSet_default>();
            }
        }
        
        public static SteamVR_Input_ActionSet_gemAbilities gemAbilities
        {
            get
            {
                return SteamVR_Actions.p_gemAbilities.GetCopy<SteamVR_Input_ActionSet_gemAbilities>();
            }
        }
        
        public static SteamVR_Input_ActionSet_locomotion locomotion
        {
            get
            {
                return SteamVR_Actions.p_locomotion.GetCopy<SteamVR_Input_ActionSet_locomotion>();
            }
        }
        
        private static void StartPreInitActionSets()
        {
            SteamVR_Actions.p__default = ((SteamVR_Input_ActionSet_default)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_default>("/actions/default")));
            SteamVR_Actions.p_gemAbilities = ((SteamVR_Input_ActionSet_gemAbilities)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_gemAbilities>("/actions/gemAbilities")));
            SteamVR_Actions.p_locomotion = ((SteamVR_Input_ActionSet_locomotion)(SteamVR_ActionSet.Create<SteamVR_Input_ActionSet_locomotion>("/actions/locomotion")));
            Valve.VR.SteamVR_Input.actionSets = new Valve.VR.SteamVR_ActionSet[] {
                    SteamVR_Actions._default,
                    SteamVR_Actions.gemAbilities,
                    SteamVR_Actions.locomotion};
        }
    }
}
