using System;
using System.Linq;
using JoyWay.Registries;
using UnityEngine.AI;
using Random = System.Random;

public class GameMain : Singleton<GameMain> {
	public SettingsAsset settingsAsset;
	public DeveloperSettingsAsset developerSettingsAsset;
	public AssetsDatabase db;
	public static SettingsAsset settings;
	public static Random RNG;

	public static Owner defaultOwner;

	// TODO: Перебазироваться на состояния игры
	public static bool IsMainLoop() => LevelManager.currentScene == ScenesList.AutoGenerated;

	protected override void Awake() {
		RNG = new Random();
		base.Awake();
		db.Init();
		defaultOwner = GetComponent<Owner>();
		Owner.Wolrd = defaultOwner;
		settings = settingsAsset;
		settings.LoadFromFile();

		LevelManager.LoadDungeon();
	}


	private void OnApplicationQuit() {
		settings.SaveProgress();
	}
}